server:
  port: 8082
  ssl:
    key-store: classpath:certs/order-service.p12
    key-store-password: ${ORDER_SERVICE_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: order-service

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/microservices-realm

product-service:
  base-url: ${PRODUCT_SERVICE_BASE_URL:https://localhost:8081}
  ssl:
    key-store: classpath:certs/client.p12
    key-store-password: ${ORDER_SERVICE_CLIENT_KEYSTORE_PASSWORD:changeit}
    key-store-type: PKCS12
    trust-store: classpath:certs/truststore.p12
    trust-store-password: ${ORDER_SERVICE_TRUSTSTORE_PASSWORD:changeit}
    trust-store-type: PKCS12
