name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --source . --redact

  sca:
    needs: secret-scan # Only run if no secrets found
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@v1.1.0 # Fixed version
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
          JAVA_HOME: /opt/jdk 
        with:
          project: DevSecOpsDevoir
          path: .
          format: "HTML"
          out: dependency-check-report
          args: >-
            --failOnCVSS 7
            --scan gateway
            --scan product-service
            --scan order-service
            --scan react-app
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report

  sast:
    needs: secret-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      
      # Build all modules to provide binaries for a better Sonar scan
      - name: Build Microservices
        run: |
          mvn -q -DskipTests clean package -pl gateway,product-service,order-service -am

      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@v3 # Upgraded version
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}